import React from "react";

export default function Content() {
  return (
    <>
      <p>
        JSON (JavaScript Object Notation) is a lightweight, text-based data-interchange format. It is easy for humans to read and write and easy for machines to parse and generate. However, raw JSON generated by APIs is often minified into a single line, making it hard to inspect.
      </p>
      <p className="font-semibold text-foreground mt-4">Features of this Formatter:</p>
      <ul className="list-disc pl-4 mt-2 space-y-1">
        <li>Format minified JSON to make it human-readable.</li>
        <li>Minify formatted JSON to compress space for API requests.</li>
        <li>Validate JSON strings to ensure correctness of keys, quotes, and commas.</li>
        <li>One-click copy to clipboard.</li>
      </ul>
      <p className="mt-4 text-xs">
        Ensure your JSON conforms to standard specifications: string keys must be surrounded by double quotes, and trailing commas are not allowed.
      </p>
    </>
  );
}
